name: Build Equipment Tracker Installer

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      
    - name: Restore NuGet packages
      run: nuget restore EquipmentTracker.sln
      
    - name: Build solution
      run: msbuild EquipmentTracker.sln /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.6
      
    - name: Create output directory
      run: |
        New-Item -ItemType Directory -Force -Path .\installer\output
        Copy-Item -Path .\bin\Release\* -Destination .\installer\output\ -Recurse
      
    - name: Download WiX Toolset
      run: |
        Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix.zip"
        Expand-Archive -Path "wix.zip" -DestinationPath "C:\wix"
        
    - name: Build installer
      run: |
        $env:PATH = "C:\wix;" + $env:PATH
        candle.exe -ext WixUIExtension -ext WixUtilExtension installer\setup.wxs -o installer\setup.wixobj
        light.exe -ext WixUIExtension -ext WixUtilExtension installer\setup.wixobj -o installer\EquipmentTrackerSetup.msi
      
    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: EquipmentTrackerInstaller
        path: installer\EquipmentTrackerSetup.msi
        retention-days: 30
